### ISSUE TITLE
Crash on opening a .xlsx file - Argument unknown: 'use_iterators'

### ISSUE THREAD

**Issue by florinj** [jokey2k/tablereader#3]
Hi Markus,

Please help.
Tried to open a .xlsx file but I couldn't.
I am an Ubuntu-Mate 14.04(trusty) user.

Python 3.4 console
>\>\>\> from tablereader import TableReader as tr
>\>\>\> r = tr('Asociatii0917.xlsx',sheet='Asociatii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tablereader/__init__.py", line 190, in __init__
    self.reader.reader = XLSXReader(filename, sheet)
  File "/usr/local/lib/python3.4/dist-packages/tablereader/__init__.py", line 84, in __init__
    self._reader = openpyxl.load_workbook(filename, use_iterators=True)
TypeError: load_workbook() got an unexpected keyword argument 'use_iterators'

Module versions: openpyxl (2.4.8), tablereader (1.0.4) installed using pip3

and the same in Python 2.7 console
>\>\>\> from tablereader import TableReader as tr
>\>\>\> r = tr('Asociatii0917.xlsx',sheet='Asociatii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tablereader/__init__.py", line 190, in __init__
    self.reader.reader = XLSXReader(filename, sheet)
  File "/usr/local/lib/python2.7/dist-packages/tablereader/__init__.py", line 84, in __init__
    self._reader = openpyxl.load_workbook(filename, use_iterators=True)
TypeError: load_workbook() got an unexpected keyword argument 'use_iterators'

Module versions: openpyxl (2.4.8), tablereader (1.0.4) installed using pip

Thank you.
Best regards,
F.J.

**Comment by jokey2k** [comment]
Sorry, took some time, but is fixed now
